### ISSUE TITLE
Functionality outside jupyter notebook

### ISSUE THREAD

**Issue by ricoms** [VIDA-NYU/PipelineVis#8]
The output of plot_pipeline_matrix is interesting to keep as an explanatory artifact of the final model. Although this artifact would be much more interesting if it were a standalone visualization instead of a notebook dependent widget.

**Comment by jorgehpo** [comment]
Hi @ricoms , you can get a standalone version of the visualization with the function get_pipeline_profiler_html, for example:

`
html = PipelineProfiler.get_pipeline_profiler_html(PipelineProfiler.get_heartstatlog_data())
with open("output.html", "w") as f:
    f.write(html)
`

However, you will not be able to merge pipelines (select multiple rows), because we use Python to do this.
